### ISSUE TITLE
Find solution for replacement of HTTPS protocol for our git course

### ISSUE THREAD

**Issue by jonasjucker** [C2SM/git-course#12]

**Comment by AnnikaLau** [comment]
`export GITHUB_USER=magickatt
export GITHUB_TOKEN=secret
export GITHUB_REPOSITORY=C2SM/git-course
git clone [https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}](https://$%7BGITHUB_USER%7D:$%7BGITHUB_TOKEN%7D@github.com/$%7BGITHUB_REPOSITORY%7D)`
