### ISSUE TITLE
Ensure that the `conference_planning` folder is cloned outside of `git-course` repo

### ISSUE THREAD

**Issue by mjaehn** [C2SM/git-course#55]
Adapt `helpers.sh` for that

**Comment by AnnikaLau** [comment]
Note: jupyter notebook need to be opened in parent folder of the git-course to be able to make changes to the files in the beginners part.

**Comment by AnnikaLau** [comment]
Commit ccfbf3818d5f15cee5042c210b40a4a25dfcb424 creates working directory outside of git-course for the beginners course.

**Comment by jonasjucker** [comment]
https://github.com/C2SM/git-course/commit/a34a41c2aea98f967e3c08876f72b9341dab0783 implements this for advanced course using
`script_dir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )`

**Comment by jonasjucker** [comment]
The solution for advanced course is safer than what we currently use in begginers:
`script_dir=$(pwd)`
Therefore keep this issue open an change for beginners course next year too

**Comment by fabianschoeni** [comment]
@jonasjucker is this solved?

**Comment by jonasjucker** [comment]
No, but I can have a look at it this week

**Comment by fabianschoeni** [comment]
> No, but I can have a look at it this week

thanks!

**Comment by AnnikaLau** [comment]
This commit 8ecef6d1f68c2fccbf0221411aba32f5212177b4 should fix the issue that `dir_at_startup` is no longer the Exercise folder but the folder where the helpers file is located.
