### ISSUE TITLE
[Slides/Exercises] Is `git subtree` still relevant?

### ISSUE THREAD

**Issue by mjaehn** [C2SM/git-course#56]

**Comment by mjaehn** [comment]
@jonasjucker @AnnikaLau What is your opinion on that?

**Comment by AnnikaLau** [comment]
At least I haven't heard of anybody using it. So probably not?

**Comment by mjaehn** [comment]
Removing `git subtree` means that we get rid of Exercise 8 and the corresponding parts in the presentation. In that case, we only deal with submodules in the "Part 3: Nesting Git Repositories" section. 

As a replacement, we could add something interesting that users might integrate into their workflows. My suggestion would be [Custom Git Hooks](https://github.com/CompSciLauren/awesome-git-hooks). This could be integrated in the "Part 2: Git Workflow" section.

What do you think?

**Comment by jonasjucker** [comment]
Wow did not know this is so easy to integrate :-)

**Comment by AnnikaLau** [comment]
I like it
