### ISSUE TITLE
Inform people better that the init_exercise function will navigate them into a different folder

### ISSUE THREAD

**Issue by AnnikaLau** [C2SM/git-course#63]
People got confused because they were no longer in the Exercise folder when they were doing the exercises. Make it clearer that it is meant to be like this.

**Comment by fabianschoeni** [comment]
Commit a2039f1d13bcd21307a64054e44a924c1a555f29 echoes some additional information for the init_exercise function.

**Comment by AnnikaLau** [comment]
We would need the same for `init_simple_repo_remote` as it navigates you to _conference_planning_

**Comment by fabianschoeni** [comment]
Ok, I did something similar to `init_simple_repo_remote` and `init_repo_remote` here: 6387dabbdfd7d793900ff263b72e2ec7124bc4f8

**Comment by AnnikaLau** [comment]
Nice!
Is it also possible to have this message in bold letters or in a way that it doesn't get lost among the other messages?

**Comment by fabianschoeni** [comment]
What's your preference?

![image](https://github.com/C2SM/git-course/assets/91718464/929ddaf9-9b42-441d-acda-97cac2c87e00)

**Comment by fabianschoeni** [comment]
Alright, we have bold and red messages now: 907d5914399848d10d9696ae67944607fb7e3aca

**Comment by fabianschoeni** [comment]
solved by 966c597cb6ec95135d3397a242d87755d9c9c68f

**Comment by mjaehn** [comment]
LGTM
