### ISSUE TITLE
The helpers.sh file does not work for old Git versions

### ISSUE THREAD

**Issue by AnnikaLau** [C2SM/git-course#64]
For users having an old Git version, the helper file doesn't always work correctly, as the old version doesn't know the `git switch` command and has the `master` branch as default (cannot be changed as in the newer versions).

Make users get the new version or have another option in the helpers file?

**Comment by AnnikaLau** [comment]
`git switch` does also not work with old git versions.

**Comment by fabianschoeni** [comment]
solved by 0a3d8ce621dbe05e37ef09e802ca3974d3c4875a

**Comment by mjaehn** [comment]
LGTM
