### ISSUE TITLE
Remove "Navigate to the remote repository" in Exercise 5

### ISSUE THREAD

**Issue by AnnikaLau** [C2SM/git-course#67]
Users got confused with the remote repository, which is stored locally, which is also not a typical use-case. Better remove it.

**Comment by fabianschoeni** [comment]
607f723d567f8b8d0d445e1b9cc69beafceb2eaf fixes this

**Comment by AnnikaLau** [comment]
You cannot switch to `updated_schedules` in the remote repository, if you don't navigate there. So if we don't want the users to navigate there, they cannot change to the other branch. Therefore, we should probably delete the whole last part starting at _Now we go to the folder .../remote_

**Comment by fabianschoeni** [comment]
Yes, that's right, I only deleted half of what the issue asked for. But if I had deleted the whole thing, it would no longer work as you describe. Don't you think that by deleting the whole last part, we lose an important part of how branches work? Or are we dealing with that in other parts of the exercises anyway?

**Comment by AnnikaLau** [comment]
I actually don't think that information is important at all. Usually the remote repository is actually remote. If you go onto GitHub for example, you will directly see on which branch you are on and probably not wonder why the file isn't changed in the main branch.

**Comment by fabianschoeni** [comment]
Alright, fine with me.

**Comment by fabianschoeni** [comment]
solved by 7bbd7ce0bf8388100bf616fb4ded9e32e652481b

**Comment by mjaehn** [comment]
LGTM
