### ISSUE TITLE
The helper function commit_to_remote_by_third_party works incorrectly

### ISSUE THREAD

**Issue by AnnikaLau** [C2SM/git-course#75]
The helper function `commit_to_remote_by_third_party` creates empty schedule in schedule_day.txt on the remote. It should instead create the same file as the in schedule_day1.txt on the local repo with the first event changed.

Double check also what `--ours` and `--theirs` does when solving a merge request of a `git pull`.

**Comment by fabianschoeni** [comment]
dbfcd1f3ef263a41ffb6ee4138ffc53eaaa73a58 fixes the creation of the schedule_day1.txt on the remote repo.

**Comment by AnnikaLau** [comment]
This d886537f7b4bcdf0592a629ddd26c3d576809742 should work now.

**Comment by AnnikaLau** [comment]
@mjaehn can you check?
