### ISSUE TITLE
Check if README is up to date

### ISSUE THREAD

**Issue by mjaehn** [C2SM/git-course#90]

**Comment by fabianschoeni** [comment]
We should revise the code blocks in the readme so that they do not contain instructions but only code, so that the copy to clipboard function can be used.

**Comment by mjaehn** [comment]
Do you think this is necessary? The instructions within the code blocks are comments. So the user is actually able to use the clipboard to copy/paste.

**Comment by AnnikaLau** [comment]
Actually in my terminal on Mac, it gave me an error when copying also the comments.

**Comment by mjaehn** [comment]
So what do we do here? In `bash`, every is running fine and it has the same style as the cells in the Jupyter notebook. I vote for keeping it as is.
