### ISSUE TITLE
Clarify in which folder "git submodule update --remote --merge" needs to run in Exercise 8

### ISSUE THREAD

**Issue by jonasjucker** [C2SM/git-course#94]
In https://github.com/C2SM/git-course/blob/main/advanced/Exercise_8_git-submodule.md last Section it says 

> Once you have done this, go to back to the terminal and use git submodule update to get the main repository to fetch the new commit from the posters repository.
> 
> git submodule update --remote --merge

This needs to happen in the parent folder `conference_submodules`, so I suggest adding a `cd ..` to the command. Within the submodule, the command silently fails so there is no way of knowing that you just did the command in the wrong folder and it hasn't actually updated the submodule.

**Comment by AnnikaLau** [comment]
Done with https://github.com/C2SM/git-course/commit/dd584171cb95d4f82c1df712910b29d831bdfb91
