### ISSUE TITLE
Change "git restore --source=<commit_hash>" to "git restore -s <commit_hash>"?

### ISSUE THREAD

**Issue by AnnikaLau** [C2SM/git-course#99]

**Comment by fabianschoeni** [comment]
Well, yes, we can change that. I thought the --source variant was a bit more intuitive. Will the --source method be deprecated in the future?

**Comment by AnnikaLau** [comment]
No I don't think so but it's longer than the `-s` variant. I thought `-s` could be more intuitiv as we don't use something with `=` otherwise. I asked Michael, he also thinks the `-s` variant is nicer.

**Comment by AnnikaLau** [comment]
Add explanation `-s` = `--source=`

**Comment by fabianschoeni** [comment]
solved by 1db94fd8783714e7c4ee8125b5034cbb329b85da

**Comment by mjaehn** [comment]
LGTM and can be closed imho.
